---
- name: Generate Worker Kubeconfig
  command: bash -c "kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=ca.pem --embed-certs=true --server=https://{{ k8sv161_lb_ip }}:6443 --kubeconfig={{ item }}.kubeconfig"
  args:
    chdir: /vagrant
    creates: /vagrant/{{ item }}.kubeconfig
    
- name: Set credentials into Worker.kubeconfig
  command: bash -c "kubectl config set-credentials system:node:{{ item }} --client-certificate={{ item }}.pem --client-key={{ item }}-key.pem --embed-certs=true --kubeconfig={{ item }}.kubeconfig"
  args:
    chdir: /vagrant

- name: Set context into Worker.kubeconfig
  command: bash -c "kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:node:{{ item }} --kubeconfig={{ item }}.kubeconfig"
  args:
    chdir: /vagrant


- name: Set use-context into Worker.kubeconfig
  command: bash -c "kubectl config use-context default --kubeconfig={{ item }}.kubeconfig"
  args:
    chdir: /vagrant
