---
- name: Create Worker CSR JSON file
  template:
    src: worker-csr.json
    dest: "/tmp/{{ item }}-csr.json"
    
- name: Generate Worker Certificate
  command: bash -c "cfssl gencert -ca=/vagrant/ca.pem -ca-key=/vagrant/ca-key.pem -config=/tmp/ca-config.json -hostname={{ item }},{{ k8sv161_lb_ip }},{{ ansible_eth1.ipv4.address }} -profile=kubernetes /tmp/{{ item }}-csr.json | cfssljson -bare {{ item }}"
  args:
    chdir: /vagrant
    creates: /vagrant/{{ item }}-key.pem
