---
# tasks file for install_nginx_pods

- name: Deploy 3 NGINX replicas
  command: bash -c 'kubectl run nginx --image=nginx --port=80 --replicas=3'

- name: Expose NGINX deployment
  command: bash -c 'kubectl expose deployment nginx --type NodePort'

- name: Deploy 3 KUARD replicas
  command: bash -c 'kubectl run kuard --image=gcr.io/kuar-demo/kuard-amd64:v0.6-3 --port=8080 --replicas=3'

- name: Expose KUARD deployment
  command: bash -c 'kubectl expose deployment kuard --type NodePort'
