---
# tasks file for install_haproxy

- name: install the latest version of haproxy
  package:
    name: haproxy
    state: latest

- name: Configure HAProxy as the Load Balancer for K8s cluster
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: "# BEGIN Adding Master IP addresses"
    block: |
       frontend https_k8s
          bind *:6443
          mode tcp
          default_backend bk_k8s

       backend bk_k8s
          mode tcp
          balance roundrobin
          server k8sc1 {{ k8s_c1_ip }}
          server k8sc2 {{ k8s_c2_ip }}

- name: Enable SELinux HAProxy
  command: bash -c "setsebool -P haproxy_connect_any=1"
  when: ansible_distribution == "CentOS" 

- name: Restarts HAProxy Service
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: haproxy
